export type Lang = "es" | "en";

export const copy = {
  es: {
    nav_home: "Inicio",
    nav_about: "Nosotros",
    nav_app: "App",
    nav_cities: "Ciudades",
    nav_download: "Descargar",
    nav_login: "Log In",
    nav_signup: "Inicia gratis",

    hero_tab_pro: "⚡ Pro",
    hero_tab_property: "🏢 Property",
    hero_tab_facility: "🔧 Facility",
    hero_tab_security: "🔐 Security",
    hero_pro_badge: "✦ Más completo",

    pro_title: "La solución todo-en-uno para tu propiedad",
    pro_sub: "Combina Property, Facility y Security en una sola plataforma.",
    pro_f1: "Administración financiera",
    pro_f2: "Gestión de activos",
    pro_f3: "Control de accesos",
    pro_f4: "Comunidad digital",
    pro_cta: "Inicia con Pro gratis",

    property_title: "Administra tu propiedad sin complicaciones",
    property_sub: "Control financiero, expedientes y pagos en línea.",
    property_f1: "Ingresos y egresos",
    property_f2: "Expedientes por unidad",
    property_f3: "Pagos en línea",
    property_f4: "Avisos",
    property_cta: "Prueba Property gratis",

    facility_title: "Operación y mantenimiento bajo control",
    facility_sub: "Registra activos, gestiona tickets y da seguimiento con QR.",
    facility_f1: "Activos con QR",
    facility_f2: "Tickets de mantenimiento",
    facility_f3: "Calendario",
    facility_f4: "Reportes",
    facility_cta: "Prueba Facility gratis",

    security_title: "Seguridad digital para tu acceso",
    security_sub: "Controla quién entra y sale con QR y accesos digitales.",
    security_f1: "Control de accesos QR",
    security_f2: "Registro de visitas",
    security_f3: "Alertas en tiempo real",
    security_f4: "Bitácora digital",
    security_cta: "Prueba Security gratis",

    social_proof: "+50,000 unidades administradas · 11 países · iOS, Android y Web",

    features_title: "Todo lo que tu propiedad necesita",
    feature_finance_t: "Finanzas",
    feature_finance_d: "Ingresos, egresos y pagos en un panel claro.",
    feature_payments_t: "Pagos en línea",
    feature_payments_d: "Cobra con tarjeta, SPEI y referencias bancarias.",
    feature_access_t: "Accesos QR",
    feature_access_d: "Entradas digitales para residentes y visitas.",
    feature_tickets_t: "Tickets",
    feature_tickets_d: "Reporta y da seguimiento al mantenimiento.",
    feature_assets_t: "Activos",
    feature_assets_d: "Inventario con etiquetas QR escaneables.",
    feature_comms_t: "Comunicación",
    feature_comms_d: "Avisos y chat con tu comunidad.",
    feature_reports_t: "Reportes",
    feature_reports_d: "Información clara para tomar decisiones.",
    feature_mobile_t: "Móvil y Web",
    feature_mobile_d: "Disponible en iOS, Android y navegador.",

    how_title: "Empieza en minutos",
    how_step1: "Crea tu propiedad",
    how_step2: "Da acceso a tu comunidad",
    how_step3: "¡Digitaliza tu propiedad!",

    download_title: "Tu propiedad ya usa Kiperfy — baja la app gratuita",
    download_sub: "Disponible en las tres tiendas principales.",

    footer_rights: "Todos los derechos reservados.",
    footer_country: "País",
    footer_privacy: "Privacidad",
    footer_terms: "Términos",

    // Login modal
    login_headline: "Bienvenido de vuelta",
    login_sub: "Ingresa con tu cuenta Kiperfy",
    login_or: "— o continúa con —",
    login_google: "Continuar con Google",
    login_email_ph: "Correo electrónico",
    login_password_ph: "Contraseña",
    login_forgot: "¿Olvidaste tu contraseña?",
    login_cta: "Iniciar sesión",
    login_footer: "¿No tienes cuenta?",
    login_footer_link: "Regístrate gratis",

    // Signup
    signup_step1_title: "Crea tu cuenta",
    signup_step1_sub: "Empieza gratis, sin tarjeta de crédito",
    signup_step1_google: "Registrarse con Google",
    signup_step1_or: "— o regístrate con correo —",
    signup_step1_name: "Nombre completo",
    signup_step1_email: "Correo electrónico",
    signup_step1_password: "Contraseña",
    signup_step1_password_hint: "Mínimo 8 caracteres",
    signup_step1_confirm: "Confirmar contraseña",
    signup_continue: "Continuar",
    signup_step1_footer: "¿Ya tienes cuenta?",
    signup_step1_footer_link: "Inicia sesión",

    signup_step2_title: "Tu propiedad",
    signup_step2_sub: "Cuéntanos sobre el lugar que vas a administrar",
    signup_step2_propname: "Nombre de la propiedad",
    signup_step2_propname_ph: "Ej. Torre Reforma 180",
    signup_step2_propcount: "Número de propiedades",
    signup_step2_units: "Número de unidades",
    signup_step2_units_ph: "Ej. 48",
    signup_step2_role: "Rol",
    signup_step2_role_val: "Administrador",
    signup_step2_role_tip: "El primer usuario siempre es Administrador",

    signup_step3_title: "¿Con qué quieres empezar?",
    signup_step3_sub: "Todos los planes incluyen 14 días gratis",
    signup_step3_trial_badge: "14 días gratis",
    signup_step3_recommended: "Recomendado",
    signup_step3_cta: "Iniciar prueba gratis",
    signup_step3_fineprint: "Sin tarjeta de crédito · Cancela cuando quieras",
    signup_back: "← Atrás",

    plan_pro: "Pro",
    plan_pro_f1: "Todo incluido",
    plan_pro_f2: "Property + Facility + Security",
    plan_pro_f3: "Soporte prioritario",

    plan_property: "Property",
    plan_property_f1: "Control financiero",
    plan_property_f2: "Expedientes",
    plan_property_f3: "Pagos en línea",

    plan_facility: "Facility",
    plan_facility_f1: "Gestión de activos",
    plan_facility_f2: "Tickets",
    plan_facility_f3: "Calendario QR",

    plan_security: "Security",
    plan_security_f1: "Control de accesos",
    plan_security_f2: "Visitas",
    plan_security_f3: "Bitácora digital",

    modal_close: "Cerrar",
    show_password: "Mostrar contraseña",
  },
  en: {
    nav_home: "Home",
    nav_about: "About",
    nav_app: "App",
    nav_cities: "Cities",
    nav_download: "Download",
    nav_login: "Log In",
    nav_signup: "Start free",

    hero_tab_pro: "⚡ Pro",
    hero_tab_property: "🏢 Property",
    hero_tab_facility: "🔧 Facility",
    hero_tab_security: "🔐 Security",
    hero_pro_badge: "✦ Most complete",

    pro_title: "The all-in-one solution for your property",
    pro_sub: "Combine Property, Facility and Security in one platform.",
    pro_f1: "Financial management",
    pro_f2: "Asset management",
    pro_f3: "Access control",
    pro_f4: "Digital community",
    pro_cta: "Start with Pro free",

    property_title: "Manage your property effortlessly",
    property_sub: "Financial control, records and online payments.",
    property_f1: "Income & expenses",
    property_f2: "Unit records",
    property_f3: "Online payments",
    property_f4: "Announcements",
    property_cta: "Try Property free",

    facility_title: "Operations and maintenance under control",
    facility_sub: "Track assets, manage tickets and follow up with QR codes.",
    facility_f1: "QR-tagged assets",
    facility_f2: "Maintenance tickets",
    facility_f3: "Service calendar",
    facility_f4: "Reports",
    facility_cta: "Try Facility free",

    security_title: "Digital security for your access points",
    security_sub: "Control who enters and exits with QR codes and digital access.",
    security_f1: "QR access control",
    security_f2: "Visitor log",
    security_f3: "Real-time alerts",
    security_f4: "Digital audit trail",
    security_cta: "Try Security free",

    social_proof: "+50,000 units managed · 11 countries · iOS, Android & Web",

    features_title: "Everything your property needs",
    feature_finance_t: "Finance",
    feature_finance_d: "Income, expenses and payments in one clear panel.",
    feature_payments_t: "Online payments",
    feature_payments_d: "Charge by card, bank transfer and references.",
    feature_access_t: "QR access",
    feature_access_d: "Digital entry for residents and visitors.",
    feature_tickets_t: "Tickets",
    feature_tickets_d: "Report and follow up on maintenance.",
    feature_assets_t: "Assets",
    feature_assets_d: "Inventory with scannable QR labels.",
    feature_comms_t: "Communication",
    feature_comms_d: "Announcements and chat with your community.",
    feature_reports_t: "Reports",
    feature_reports_d: "Clear insights to make decisions.",
    feature_mobile_t: "Mobile & Web",
    feature_mobile_d: "Available on iOS, Android and browser.",

    how_title: "Get started in minutes",
    how_step1: "Create your property",
    how_step2: "Invite your community",
    how_step3: "Your property is now digital!",

    download_title: "Your property uses Kiperfy — download the free app",
    download_sub: "Available on all three major stores.",

    footer_rights: "All rights reserved.",
    footer_country: "Country",
    footer_privacy: "Privacy",
    footer_terms: "Terms",

    login_headline: "Welcome back",
    login_sub: "Sign in to your Kiperfy account",
    login_or: "— or continue with —",
    login_google: "Continue with Google",
    login_email_ph: "Email address",
    login_password_ph: "Password",
    login_forgot: "Forgot your password?",
    login_cta: "Sign in",
    login_footer: "No account?",
    login_footer_link: "Sign up free",

    signup_step1_title: "Create your account",
    signup_step1_sub: "Start free, no credit card needed",
    signup_step1_google: "Sign up with Google",
    signup_step1_or: "— or sign up with email —",
    signup_step1_name: "Full name",
    signup_step1_email: "Email address",
    signup_step1_password: "Password",
    signup_step1_password_hint: "Minimum 8 characters",
    signup_step1_confirm: "Confirm password",
    signup_continue: "Continue",
    signup_step1_footer: "Already have an account?",
    signup_step1_footer_link: "Sign in",

    signup_step2_title: "Your property",
    signup_step2_sub: "Tell us about the property you'll manage",
    signup_step2_propname: "Property name",
    signup_step2_propname_ph: "e.g. Reforma Tower 180",
    signup_step2_propcount: "Number of properties",
    signup_step2_units: "Number of units",
    signup_step2_units_ph: "e.g. 48",
    signup_step2_role: "Role",
    signup_step2_role_val: "Administrator",
    signup_step2_role_tip: "First user is always Administrator",

    signup_step3_title: "What would you like to try?",
    signup_step3_sub: "All plans include a 14-day free trial",
    signup_step3_trial_badge: "14 days free",
    signup_step3_recommended: "Recommended",
    signup_step3_cta: "Start free trial",
    signup_step3_fineprint: "No credit card · Cancel anytime",
    signup_back: "← Back",

    plan_pro: "Pro",
    plan_pro_f1: "Everything included",
    plan_pro_f2: "Property + Facility + Security",
    plan_pro_f3: "Priority support",

    plan_property: "Property",
    plan_property_f1: "Financial control",
    plan_property_f2: "Unit records",
    plan_property_f3: "Online payments",

    plan_facility: "Facility",
    plan_facility_f1: "Asset management",
    plan_facility_f2: "Tickets",
    plan_facility_f3: "QR calendar",

    plan_security: "Security",
    plan_security_f1: "Access control",
    plan_security_f2: "Visitors",
    plan_security_f3: "Digital audit trail",

    modal_close: "Close",
    show_password: "Show password",
  },
} as const;

export type CopyKey = keyof typeof copy.es;
