export type Lang = "es" | "en";

export const copy = {
  es: {
    nav_modules: "Módulos",
    nav_app: "App",
    nav_login: "Log In",
    nav_signup: "Iniciar gratis",

    hero_tab_pro: "Pro",
    hero_tab_property: "Property",
    hero_tab_facility: "Facility",
    hero_tab_security: "Security",
    hero_pro_badge: "Más completo",
    hero_cta: "Comenzar gratis",
    hero_cta_fineprint: "Gratis para siempre · Sube de plan cuando lo necesites",
    hero_toast_payment: "Pago recibido",
    hero_toast_access: "Acceso aprobado",
    hero_toast_maintenance: "Mantenimiento completado",
    hero_media_alt: "Vista del producto Kiperfy",
    hero_media_placeholder_title: "Plataforma en acción",
    hero_media_placeholder_hint: "Añade hero-product.mp4, .webm o .gif en /public",
    pro_heading: "",
    pro_hook: "¿Sigues operando tu propiedad con WhatsApp, Excel y sistemas desconectados?",
    pro_sub:
      "Kiperfy PRO centraliza administración, mantenimiento, seguridad, comunicación y recompensas en una sola plataforma inteligente para propiedades modernas.",
    pro_f1: "Administración financiera",
    pro_f2: "Gestión de activos",
    pro_f3: "Control de accesos",
    pro_f4: "Comunidad digital",
    pro_cta: "Inicia con Pro gratis",

    property_heading: "",
    property_hook:
      "¿Frustrado por pagos atrasados, procesos manuales y comunicación interminable con usuarios?",
    property_sub:
      "Kiperfy Property Management simplifica cobranza, comunicación, estados de cuenta y operación diaria desde una sola plataforma centralizada.",
    property_f1: "Ingresos y egresos",
    property_f2: "Expedientes por unidad",
    property_f3: "Pagos en línea",
    property_f4: "Avisos",
    property_cta: "Prueba Property gratis",

    facility_heading: "",
    facility_hook:
      "¿Sigues administrando mantenimientos, equipos y órdenes de trabajo entre llamadas, chats y Excel?",
    facility_sub:
      "Kiperfy Facility Management centraliza mantenimientos, tareas preventivas, seguimiento de equipos y órdenes de trabajo con visibilidad en tiempo real.",
    facility_f1: "Activos con QR",
    facility_f2: "Tickets de mantenimiento",
    facility_f3: "Calendario",
    facility_f4: "Reportes",
    facility_cta: "Prueba Facility gratis",

    security_heading: "",
    security_hook:
      "¿Sigues operando la seguridad de tu propiedad con accesos desconectados y registros manuales?",
    security_sub:
      "Kiperfy Security Management centraliza control de accesos, visitantes, QR, alertas y operación de seguridad en una sola plataforma conectada.",
    security_f1: "Control de accesos QR",
    security_f2: "Registro de visitas",
    security_f3: "Alertas en tiempo real",
    security_f4: "Bitácora digital",
    security_cta: "Prueba Security gratis",

    metrics_title: "Operando a escala real desde 2018",
    metric_statements: "Estados de Cuenta",
    metric_users: "Usuarios",
    metric_maintenance: "Mantenimientos",
    metric_access: "Accesos",
    metric_cashback: "Puntos y Cashback distribuidos",
    metric_retention: "Clientes que renuevan año tras año",

    team_title: "Tu equipo gana mientras trabaja",
    team_subtitle: "Genera puntos para cashback y tarjetas de regalo",
    team_stat_pill: "10,000 puntos distribuidos este mes",
    team_col1_title: "Administradores",
    team_col1_body:
      "Gestiona cobros, reportes y comunicación. Acumula puntos con cada tarea completada.",
    team_col2_title: "Técnicos",
    team_col2_body:
      "Sube tus órdenes de trabajo desde el celular. Recibe cashback por cada tarea registrada.",
    team_col3_title: "Seguridad",
    team_col3_body:
      "Registra accesos y visitantes en tiempo real. Tus registros generan puntos automáticamente.",

    lead_title: "Descubre cómo Kiperfy se adapta a tu propiedad",
    lead_subtitle: "3 preguntas. Un reporte personalizado para tu propiedad.",
    lead_back: "Atrás",
    lead_next: "Siguiente",
    lead_q1: "¿Cuántas unidades tiene tu propiedad?",
    lead_q1_a: "Menos de 50",
    lead_q1_b: "50 a 150",
    lead_q1_c: "150 a 500",
    lead_q1_d: "Más de 500",
    lead_q2: "¿Cuál es tu mayor problema operativo hoy?",
    lead_q2_a: "Cobros y morosidad",
    lead_q2_b: "Mantenimiento y equipos",
    lead_q2_c: "Control de accesos",
    lead_q2_d: "Comunicación con residentes",
    lead_q3: "¿Quién toma las decisiones tecnológicas en tu propiedad?",
    lead_q3_a: "El consejo lo vota",
    lead_q3_b: "El administrador decide",
    lead_q3_c: "Tenemos un responsable de sistemas",
    lead_q3_d: "No estamos seguros",
    lead_name: "Tu nombre",
    lead_email: "Correo electrónico",
    lead_submit: "Enviar mi reporte",
    lead_confirm:
      "Listo. Recibirás tu reporte personalizado en las próximas horas. Un miembro de nuestro equipo puede ayudarte a presentarlo al consejo.",
    lead_step: "Pregunta {current} de {total}",

    pricing_free: "Free",
    pricing_free_price: "$0",
    pricing_free_note: "gratis para siempre",
    pricing_free_desc: "Funciones principales · Puntos y Cashback · Unidades ilimitadas",
    pricing_pillar: "Pilar",
    pricing_pillar_price: "$150/mes",
    pricing_pillar_desc:
      "Un solo módulo a fondo. Elige entre administración de propiedad, gestión de instalaciones o control de seguridad.",
    pricing_pro: "Pro",
    pricing_pro_price: "$350/mes",
    pricing_pro_desc:
      "Todo incluido. Sin límites. Con TAD, el asistente de IA que guía a tu equipo y maximiza el uso de la plataforma.",
    pricing_cta_free: "Comenzar gratis",
    pricing_cta_pillar: "Elegir Pilar",
    pricing_cta_pro: "Comenzar con Pro",

    features_title: "Todo lo que tu propiedad necesita",
    features_pro_heading: "PRO",
    features_pro_body:
      "Kiperfy PRO centraliza administración, mantenimiento, seguridad y comunicación en una sola plataforma. Opera tu propiedad de forma más inteligente y además recompensa a todos los usuarios con Puntos y Cashback por usar la app.",
    features_property_heading: "Administración",
    features_property_body:
      "Administra pagos, estados de cuenta, comunicación y operación financiera de tu propiedad desde una sola plataforma fácil de usar para usuarios y administradores.",
    features_facility_heading: "Mantenimiento",
    features_facility_body:
      "Gestiona mantenimientos preventivos y correctivos, proveedores, tickets, incidencias y rondines con Puntos de Proximidad en tiempo real para mantener tu propiedad operando de forma eficiente para todos los usuarios.",
    features_security_heading: "Seguridad",
    features_security_body:
      "Controla accesos, visitantes, QR, bitácoras, alertas, integraciones con plumas, puertas y elevadores, además de rondines con Puntos de Proximidad desde una sola plataforma diseñada para mejorar la seguridad y operación de la propiedad para todos los usuarios.",

    preview_mobile: "App móvil",
    preview_web: "App web",
    preview_mobile_alt: "Kiperfy en smartphone mostrando ocupación y pagos de unidades",
    preview_web_alt: "Kiperfy en laptop con panel de administración y reportes",

    reviews_rating_score: "4.7/5",
    reviews_downloads_suffix: "Descargas",
    reviews_downloads_platform: "en App Store y Google Play",
    reviews_rating_subtitle: "Ranking en App store y Google Play store",
    reviews_app_store_alt: "Descargar en App Store",
    reviews_google_play_alt: "Disponible en Google Play",

    footer_rights: "Todos los derechos reservados.",
    footer_country: "País",
    footer_privacy: "Privacidad",
    footer_terms: "Términos",
    footer_cookies: "Política de cookies",
    footer_contact: "Contacto",
    footer_tagline: "Operación inteligente para propiedades modernas",
    footer_nav_title: "Enlaces rápidos",
    footer_link_features: "Plataforma",
    footer_link_modules: "Módulos",
    footer_link_app: "App",
    footer_address: "Ciudad de México, México",
    footer_phone: "+52 55 7507 5289",
    footer_email: "hola@kiperfy.com",
    footer_cta_primary: "Iniciar gratis",
    footer_cta_secondary: "Iniciar sesión",
    footer_social_whatsapp: "WhatsApp",
    footer_social_instagram: "Instagram",

    // Login modal
    login_headline: "Bienvenido de vuelta",
    login_sub: "Ingresa con tu cuenta Kiperfy",
    login_or: "— o continúa con —",
    login_google: "Continuar con Google",
    login_email_ph: "Correo electrónico",
    login_password_ph: "Contraseña",
    login_terms: "Términos y Condiciones",
    login_forgot: "¿Olvidaste tu contraseña?",
    login_cta: "Iniciar sesión",
    login_footer: "¿No tienes cuenta?",
    login_footer_link: "Regístrate gratis",

    // Signup
    signup_step1_title: "Crea tu cuenta",
    signup_step1_sub: "Empieza gratis, sin tarjeta de crédito",
    signup_step1_google: "Registrarse con Google",
    signup_step1_or: "— o regístrate con correo —",
    signup_step1_name: "Nombre completo",
    signup_step1_email: "Correo electrónico",
    signup_step1_password: "Contraseña",
    signup_step1_password_hint: "Mínimo 8 caracteres",
    signup_step1_confirm: "Confirmar contraseña",
    signup_continue: "Continuar",
    signup_step1_footer: "¿Ya tienes cuenta?",
    signup_step1_footer_link: "Inicia sesión",

    signup_step2_title: "Tu propiedad",
    signup_step2_sub: "Completa los datos de la propiedad que administrarás",
    signup_step2_propname: "Escribe el nombre de tu propiedad",
    signup_step2_propname_ph: "Ej. Torre Reforma 180",
    signup_step2_propcount: "Cantidad de propiedades",
    signup_step2_units: "Cantidad de unidades",
    signup_step2_units_ph: "Ej. 48",
    signup_step2_phone: "Teléfono de contacto",
    signup_step2_phone_ph: "Ej. +52 55 1234 5678",
    signup_step2_birthdate: "Fecha de nacimiento",

    signup_step3_title: "Selecciona el paquete que necesita tu propiedad",
    signup_step3_sub: "Todos los planes incluyen 14 días gratis",
    signup_step3_trial_badge: "14 días gratis",
    signup_step3_recommended: "Recomendado",
    signup_terms_prefix: "Acepto los",
    signup_step3_cta: "Iniciar prueba gratis",
    signup_step3_fineprint: "Sin tarjeta de crédito · Cancela cuando quieras",
    signup_back: "← Atrás",

    plan_pro: "Pro",
    plan_pro_f1: "Todo incluido",
    plan_pro_f2: "Property + Facility + Security",
    plan_pro_f3: "Soporte prioritario",

    plan_property: "Property",
    plan_property_f1: "Control financiero",
    plan_property_f2: "Expedientes",
    plan_property_f3: "Pagos en línea",

    plan_facility: "Facility",
    plan_facility_f1: "Gestión de activos",
    plan_facility_f2: "Tickets",
    plan_facility_f3: "Calendario QR",

    plan_security: "Security",
    plan_security_f1: "Control de accesos",
    plan_security_f2: "Visitas",
    plan_security_f3: "Bitácora digital",

    modal_close: "Cerrar",
    show_password: "Mostrar contraseña",
  },
  en: {
    nav_modules: "Modules",
    nav_app: "App",
    nav_login: "Log In",
    nav_signup: "Start free",

    hero_tab_pro: "Pro",
    hero_tab_property: "Property",
    hero_tab_facility: "Facility",
    hero_tab_security: "Security",
    hero_pro_badge: "Most complete",
    hero_cta: "Start free",
    hero_cta_fineprint: "Free forever · Upgrade when you need more",
    hero_toast_payment: "Payment received",
    hero_toast_access: "Access approved",
    hero_toast_maintenance: "Maintenance completed",
    hero_media_alt: "Kiperfy product preview",
    hero_media_placeholder_title: "Platform in action",
    hero_media_placeholder_hint: "Add hero-product.mp4, .webm, or .gif to /public",
    pro_heading: "",
    pro_hook:
      "Still operating your property through WhatsApp, spreadsheets and disconnected systems?",
    pro_sub:
      "Kiperfy PRO centralizes property management, maintenance, security, communication and rewards into one intelligent platform built for modern properties.",
    pro_f1: "Financial management",
    pro_f2: "Asset management",
    pro_f3: "Access control",
    pro_f4: "Digital community",
    pro_cta: "Start with Pro free",

    property_heading: "",
    property_hook:
      "Frustrated with delayed payments, manual processes and endless resident communication?",
    property_sub:
      "Kiperfy Property Management simplifies collections, communication, account statements and daily operations in one centralized platform.",
    property_f1: "Income & expenses",
    property_f2: "Unit records",
    property_f3: "Online payments",
    property_f4: "Announcements",
    property_cta: "Try Property free",

    facility_heading: "",
    facility_hook:
      "Still managing maintenance, equipment and work orders through calls, chats and spreadsheets?",
    facility_sub:
      "Kiperfy Facility Management centralizes maintenance operations, preventive tasks, equipment tracking and work orders with real-time visibility.",
    facility_f1: "QR-tagged assets",
    facility_f2: "Maintenance tickets",
    facility_f3: "Service calendar",
    facility_f4: "Reports",
    facility_cta: "Try Facility free",

    security_heading: "",
    security_hook:
      "Still operating property security with disconnected access systems and manual visitor logs?",
    security_sub:
      "Kiperfy Security Management centralizes access control, visitor management, QR access, alerts and security operations into one connected platform.",
    security_f1: "QR access control",
    security_f2: "Visitor log",
    security_f3: "Real-time alerts",
    security_f4: "Digital audit trail",
    security_cta: "Try Security free",

    metrics_title: "Operating at real scale since 2018",
    metric_statements: "Statements",
    metric_users: "Users",
    metric_maintenance: "Maintenance tickets",
    metric_access: "Access events",
    metric_cashback: "Points and Cashback distributed",
    metric_retention: "Clients who renew year after year",

    team_title: "Your team earns while they work",
    team_subtitle: "Earn points for cashback and gift cards",
    team_stat_pill: "10,000 points distributed this month",
    team_col1_title: "Property managers",
    team_col1_body:
      "Manage collections, reports and communication. Earn points with every completed task.",
    team_col2_title: "Technicians",
    team_col2_body:
      "Upload your work orders from your phone. Get cashback for every task you log.",
    team_col3_title: "Security personnel",
    team_col3_body:
      "Register access events and visitors in real time. Your logs generate points automatically.",

    lead_title: "See how Kiperfy fits your property",
    lead_subtitle: "3 questions. A custom report for your property.",
    lead_back: "Back",
    lead_next: "Next",
    lead_q1: "How many units does your property have?",
    lead_q1_a: "Less than 50",
    lead_q1_b: "50 to 150",
    lead_q1_c: "150 to 500",
    lead_q1_d: "More than 500",
    lead_q2: "What is your biggest operational challenge right now?",
    lead_q2_a: "Collections and late payments",
    lead_q2_b: "Maintenance and equipment",
    lead_q2_c: "Access control",
    lead_q2_d: "Resident communication",
    lead_q3: "Who makes technology decisions at your property?",
    lead_q3_a: "The board votes on it",
    lead_q3_b: "The property manager decides",
    lead_q3_c: "We have a dedicated systems person",
    lead_q3_d: "We are not sure yet",
    lead_name: "Your name",
    lead_email: "Email address",
    lead_submit: "Send my report",
    lead_confirm:
      "Done. You will receive your custom report within the next few hours. A member of our team can help you present it to your board.",
    lead_step: "Question {current} of {total}",

    pricing_free: "Free",
    pricing_free_price: "$0",
    pricing_free_note: "free forever",
    pricing_free_desc: "Core features · Points and Cashback · Unlimited units",
    pricing_pillar: "Pillar",
    pricing_pillar_price: "$150/mo",
    pricing_pillar_desc:
      "One module, fully unlocked. Choose between property management, facility management, or security management.",
    pricing_pro: "Pro",
    pricing_pro_price: "$350/mo",
    pricing_pro_desc:
      "Everything included. No limits. With TAD, the AI assistant that guides your team and maximizes platform usage.",
    pricing_cta_free: "Start free",
    pricing_cta_pillar: "Choose Pillar",
    pricing_cta_pro: "Start with Pro",

    features_title: "Everything your property needs",
    features_pro_heading: "PRO",
    features_pro_body:
      "Kiperfy PRO centralizes administration, maintenance, security and communication on one platform. Run your property smarter and reward every user with Points and Cashback for using the app.",
    features_property_heading: "Property",
    features_property_body:
      "Manage payments, statements, communication and financial operations from one easy-to-use platform for residents and administrators.",
    features_facility_heading: "Facility",
    features_facility_body:
      "Manage preventive and corrective maintenance, vendors, tickets, incidents and patrols with real-time Proximity Points to keep your property running efficiently for everyone.",
    features_security_heading: "Security",
    features_security_body:
      "Control access, visitors, QR codes, logs, alerts, integrations with gates, doors and elevators, plus patrols with Proximity Points from one platform built to improve security and operations for everyone.",

    preview_mobile: "Mobile App",
    preview_web: "Web App",
    preview_mobile_alt: "Kiperfy on a smartphone showing unit occupancy and payments",
    preview_web_alt: "Kiperfy on a laptop with the admin dashboard and reports",

    reviews_rating_score: "4.7/5",
    reviews_downloads_suffix: "Downloads",
    reviews_downloads_platform: "on App Store and Google Play",
    reviews_rating_subtitle: "Rating on App Store and Google Play",
    reviews_app_store_alt: "Download on the App Store",
    reviews_google_play_alt: "Get it on Google Play",

    footer_rights: "All rights reserved.",
    footer_country: "Country",
    footer_privacy: "Privacy",
    footer_terms: "Terms",
    footer_cookies: "Cookie policy",
    footer_contact: "Contact",
    footer_tagline: "Smart operations for modern properties",
    footer_nav_title: "Quick links",
    footer_link_features: "Platform",
    footer_link_modules: "Modules",
    footer_link_app: "App",
    footer_address: "Mexico City, Mexico",
    footer_phone: "+52 55 7507 5289",
    footer_email: "hello@kiperfy.com",
    footer_cta_primary: "Start free",
    footer_cta_secondary: "Sign in",
    footer_social_whatsapp: "WhatsApp",
    footer_social_instagram: "Instagram",

    login_headline: "Welcome back",
    login_sub: "Sign in to your Kiperfy account",
    login_or: "— or continue with —",
    login_google: "Continue with Google",
    login_email_ph: "Email address",
    login_password_ph: "Password",
    login_terms: "Terms and Conditions",
    login_forgot: "Forgot your password?",
    login_cta: "Sign in",
    login_footer: "No account?",
    login_footer_link: "Sign up free",

    signup_step1_title: "Create your account",
    signup_step1_sub: "Start free, no credit card needed",
    signup_step1_google: "Sign up with Google",
    signup_step1_or: "— or sign up with email —",
    signup_step1_name: "Full name",
    signup_step1_email: "Email address",
    signup_step1_password: "Password",
    signup_step1_password_hint: "Minimum 8 characters",
    signup_step1_confirm: "Confirm password",
    signup_continue: "Continue",
    signup_step1_footer: "Already have an account?",
    signup_step1_footer_link: "Sign in",

    signup_step2_title: "Your property",
    signup_step2_sub: "Fill in the details for the property you will manage",
    signup_step2_propname: "Enter your property name",
    signup_step2_propname_ph: "e.g. Reforma Tower 180",
    signup_step2_propcount: "Number of properties",
    signup_step2_units: "Number of units",
    signup_step2_units_ph: "e.g. 48",
    signup_step2_phone: "Contact phone",
    signup_step2_phone_ph: "e.g. +1 555 123 4567",
    signup_step2_birthdate: "Date of birth",

    signup_step3_title: "Select the package your property needs",
    signup_step3_sub: "All plans include a 14-day free trial",
    signup_step3_trial_badge: "14 days free",
    signup_step3_recommended: "Recommended",
    signup_terms_prefix: "I agree to the",
    signup_step3_cta: "Start free trial",
    signup_step3_fineprint: "No credit card · Cancel anytime",
    signup_back: "← Back",

    plan_pro: "Pro",
    plan_pro_f1: "Everything included",
    plan_pro_f2: "Property + Facility + Security",
    plan_pro_f3: "Priority support",

    plan_property: "Property",
    plan_property_f1: "Financial control",
    plan_property_f2: "Unit records",
    plan_property_f3: "Online payments",

    plan_facility: "Facility",
    plan_facility_f1: "Asset management",
    plan_facility_f2: "Tickets",
    plan_facility_f3: "QR calendar",

    plan_security: "Security",
    plan_security_f1: "Access control",
    plan_security_f2: "Visitors",
    plan_security_f3: "Digital audit trail",

    modal_close: "Close",
    show_password: "Show password",
  },
} as const;

export type CopyKey = keyof typeof copy.es;
